### PR TITLE
AUI-3202 Improving on accessibility issues in Calendar widget

### PR DESCRIPTION
**Pull request by orsolyaDekany**
Hello,
Accessibility evaluation tools found several issue in Calendar:
https://issues.liferay.com/browse/AUI-3202

Could you please review it?
Thank you!

### CODE REVIEW

**Comment by nhpatt** [comment]
Can you check @edalgrin or @pat270 ?

**Comment by edalgrin** [comment]
Sure!

**Comment by edalgrin** [comment]
Just started reviewing :)

**Review by edalgrin — APPROVED** [review]
I've managed to test some of the changes:







If we want to change the color of the title ☝️ we might want to change also the border 👇 

3a



If we changed this color ☝️ we would lose the visual feedback 👇 

4a

I tried to increase the difference between the "current month" and "next month" applying a black color 👇 but the result is not as intuitive as it was at the beginning, although other apps like google calendar do that too 

4b

4c

I couldn't test the JS/markup changes properly but from a quick test it seemed to be working as before

**Pull request merged**
