### PR TITLE
AUI-3204 Append "am" to times in the AM when using AM / PM format

### PR DESCRIPTION
**Pull request by mbowerman**
Hi Alloy UI team,

After this change has been committed, I plan to send a pull request to the liferay-portal repo that updates the version of Alloy-UI used, along with [this commit](https://github.com/mbowerman/liferay-portal/commit/d04104cdba4649a9a8c84e261fe2a259adb9e61c) (which fixes the issue for the Agenda view).

Please let me know if you have any questions or any disagreements about this change. Thanks!

https://issues.liferay.com/browse/AUI-3204
https://issues.liferay.com/browse/LPS-138141

### CODE REVIEW

**Review by diegonvs — APPROVED** [review]
Looks good to me! :)

Would @markocikos @carloslancha take a look too?

**Comment by carloslancha** [comment]
LGTM but I don't have too much context about AlloyUI. If you feel it's safe forward it :) Thx @mbowerman

**Comment by mbowerman** [comment]
Hi @carloslancha,

Sorry for my ignorance, but whom am I supposed to forward this pull request to?

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by mbowerman** [comment]
Hi @markocikos , thanks for reviewing and merging these changes! I have another question though if you don't mind. Now that the changes have been merged, my understanding is that a new build of alloy-ui will have to be created so that I can use it in Liferay portal. Do you know how/when the new build of alloy-ui will be created?

**Pull request merged**
